### ISSUE TITLE
panicked at 'Slot must increase'

### ISSUE THREAD

**Issue by icodezjb** [chainx-org/SherpaX#105]
call eth_getCode with 'pending'

```
2022-07-18 11:00:42.255 TRACE tokio-runtime-worker rpc: Request: {
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
        "0xfc776c74F4f992c0C9064EFe05b56a4a0370258B",
        "pending"
    ],
    "id": 1
}.    
2022-07-18 11:00:42.279 TRACE tokio-runtime-worker rpc_metrics: [http] eth_getCode call: MethodCall(MethodCall { jsonrpc: Some(V2), method: "eth_getCode", params: Array([String("0xfc776c74F4f992c0C9064EFe05b56a4a0370258B"), String("pending")]), id: Num(1) })    
2022-07-18 11:00:42.347  INFO tokio-runtime-worker substrate: ✨ Imported #2644393 (0xf304…5142)    

====================

Version: 1.4.0-dea4ed0-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:500:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:106:14
   6: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
   7: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
   8: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
   9: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
  10: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
  11: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
  12: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
  13: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
  14: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
  15: <(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnInitialize<BlockNumber>>::on_initialize
  16: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::initialize_block
  17: std::panicking::try
  18: std::thread::local::LocalKey<T>::with
  19: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  20: sc_executor::wasm_runtime::RuntimeCache::with_instance
  21: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  22: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  23: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  24: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  25: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  26: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
  27: <sherpax_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
  28: sp_api::Core::initialize_block
  29: fc_rpc::eth::pending_runtime_api
  30: <fc_rpc::eth::EthApi<B,C,P,CT,BE,H,A,F> as fc_rpc_core::eth::rpc_impl_EthApi::gen_server::EthApi>::code_at
  31: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
  32: <sc_rpc_server::middleware::RpcMiddleware as jsonrpc_core::middleware::Middleware<M>>::on_call
  33: <sc_rpc_server::middleware::RpcMiddleware as jsonrpc_core::middleware::Middleware<M>>::on_request
  34: jsonrpc_core::io::MetaIoHandler<T,S>::handle_request
  35: <jsonrpc_http_server::handler::RpcHandler<M,S> as core::future::future::Future>::poll
  36: <jsonrpc_http_server::handler::RpcHandler<M,S> as core::future::future::Future>::poll
  37: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  38: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  39: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  40: tokio::runtime::task::core::CoreStage<T>::poll
  41: tokio::runtime::task::harness::poll_future
  42: tokio::runtime::task::harness::Harness<T,S>::poll
  43: std::thread::local::LocalKey<T>::with
  44: tokio::runtime::thread_pool::worker::Context::run_task
  45: tokio::runtime::thread_pool::worker::Context::run
  46: tokio::macros::scoped_tls::ScopedKey<T>::set
  47: tokio::runtime::thread_pool::worker::run
  48: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  49: tokio::runtime::task::harness::Harness<T,S>::poll
  50: tokio::runtime::blocking::pool::Inner::run
  51: std::sys_common::backtrace::__rust_begin_short_backtrace
  52: core::ops::function::FnOnce::call_once{{vtable.shim}}
  53: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys/unix/thread.rs:106:17
  54: start_thread
             at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  55: clone
             at /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95


Thread 'tokio-runtime-worker' panicked at 'Slot must increase', /home/zjb/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/frame/aura/src/lib.rs:92

This is a bug. Please report it at:

	https://github.com/chainx-org/SherpaX

```

**Comment by icodezjb** [comment]
1. chainx and sherpax use the same version chainx-frontier, but chainx node is ok, sherpax node is panicked.
2. BLOCK AVERAGE TIME: chainx-mainet 6.000s , sherpax-mainnet 6.720s 
 https://telemetry.chainx.org/#list/0xe195ef16d0c628b5cab1486a233865def6e71f8b7814dd058a6b93a85118b796

**Comment by icodezjb** [comment]
the root cause https://github.com/paritytech/frontier/pull/814
